- name: Create manifests directory
  ansible.builtin.file:
    path: "{{ manifests_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy calico chart config manifest
  ansible.builtin.copy:
    src: "{{ rke2_calico_config_manifest }}"
    dest: "{{ manifests_dir }}"
    owner: root
    group: root
    mode: '0644'
